// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dao

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        int32
	Name      string
	BelongsTo uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	CreatedBy uuid.UUID
	UpdatedBy uuid.UUID
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type UserOrganization struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
	CreatedBy      uuid.UUID
	UpdatedBy      uuid.UUID
	DeletedBy      uuid.NullUUID
}
