version: '3.9'

services:
  posgres:
    image: postgres:14-alpine
    ports: 
      - 5432:5432
    volumes:
      - ~/.postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret!
      - POSTGRES_USER=sabida_user
      - POSTGRES_DB=sabida_db